spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/truepay?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:n3u3da!}
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  jackson:
    serialization:
      write-dates-as-timestamps: false

server:
  port: 8082
  servlet:
    session:
      cookie:
        http-only: true
        secure: false
        same-site: lax

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui

