package org.example.truepay.model;

public enum ErrorCode {
    VALIDATION_FAILED,
    INSUFFICIENT_FUNDS,
    INVALID_ACCOUNT,
    INVALID_CURRENCY,
    INVALID_AMOUNT,
    DUPLICATE_PAYMENT,
    INVALID_STATUS_TRANSITION,
    PAYMENT_NOT_FOUND,
    USER_NOT_FOUND,
    UNAUTHORIZED,
    BENEFICIARY_NOT_FOUND,
    BANK_ACCOUNT_HAS_BALANCE,
    PROCESSING_ERROR,
    NETWORK_ERROR,
    SUSPICIOUS_TRANSACTION
}

